name: DataMiner CICD NuGet Solution

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:
jobs:
  ubuntu-tests:
    name: Run all tests on Ubuntu
    runs-on: ubuntu-22.04 # Latest misses mono for .NET Framework
    steps:
      - uses: actions/checkout@v4
        
      - name: Test All
        run: dotnet test -c Release --filter TestCategory!=LocalOnly
        

  dotnet-test:
    name: Run all tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test All
        run: dotnet test -c Release --filter TestCategory!=LocalOnly

  CICD:
    needs: [ubuntu-tests, dotnet-test]
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@main
    with:
      sonarCloudProjectName: SkylineCommunications_Skyline.DataMiner.CICD.Tools.Sbom
      solutionName: "CICD.Tools.Sbom.sln"
    secrets:
      nugetApiKey: ${{ secrets.NUGETAPIKEY }}
